global:
  pullSecret:
  registry:
    url: armdocker.rnd.ericsson.se
    pullSecret:
  ingress:
    enmHost:
  enmProperties:
    COM_INF_LDAP_ADMIN_ACCESS:
    COM_INF_LDAP_ADMIN_CN:
    COM_INF_LDAP_PORT:
    COM_INF_LDAP_ROOT_SUFFIX:
    LDAP_ADMIN_CN:
    LDAP_ADMIN_PASSWORD:
    postgresql01_admin_password:
    postgres_service:
  timezone:
  persistentVolumeClaim:
    storageClass:
productNumber: CXC Placeholder
# R-State of the product. R State should match helm chart version (3.1.0 -> R2A)
# To automate it when packaging the helm chart rstate can be generated
# and below value replaced with correct R-State
productRevision: RSTATE
labels: {}
# Number of replicas(pods) to deploy
replicas-eric-enmsg-ext-app-launch-enabler: 2
images:
  eric-enmsg-ext-app-launch-enabler:
    name: eric-enmsg-ext-app-launch-enabler
    tag: VERSION
  eric-enm-httpd:
    name: eric-enmsg-ext-app-launch-enabler-httpd
    tag: VERSION
  eric-enm-monitoring:
    enabled: true
    name: eric-enm-monitoring-eap7
    tag: 1.64.0-33
  waitForCertificatesContainer:
    enabled: true
    name: enm-wait-for-certificates-container
    tag: 1.52.0-33
imageCredentials:
  repoPath: proj-enm
  pullPolicy: IfNotPresent
  pullSecret:
  registry:
    url:
securityPolicy:
  rolename: ext-app-launch-enabler
eric-enm-common-helmchart-library:
  enabled: true
## Configure the service
service:
  name: ext-app-launch-enabler
  sgname: ext-app-launch-enabler
  annotations: {}
  labels:
  xmlMountPath: "/ericsson/credm/certReqMount"
  tlsMountPath: "/ericsson/credm/tlsMount"
ingress:
  enabled: false
ingress_jboss_web_context:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
## Configure resource requests and limits
resources:
  requests:
    enabled: true
    memory: 2048Mi
    cpu: 500m
  limits:
    enabled: true
    memory: 2048Mi
    cpu: 1000m
  httpd:
    enabled: true
    requests:
      memory: 400Mi
      cpu: 250m
    limits:
      memory: 1000Mi
      cpu: 500m
  monitoring:
    enabled: true
    requests:
      memory: 200Mi
      cpu: 50m
    limits:
      memory: 300Mi
      cpu: 200m
# StartupProbe Health Check configuration.
probes:
  container:
    startupProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 10
    livenessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 2
    readinessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 30
      failureThreshold: 2
  monitoringcontainer:
    startupProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 10
    livenessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 2
  htppdcontainer:
    startupProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 10
    livenessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 2
    readinessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 30
      failureThreshold: 2
startupProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 10
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 10
# LivenessProbe Health Check configuration.
livenessProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 30
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 2
readinessProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 2
# Extra Annotations to be added to pod
podAnnotations: {}
## Tolerations for pod assignment
tolerations: []
## Affinity for pod assignment
affinity: requiredDuringSchedulingIgnoredDuringExecution
# Constrain which nodes your pod is eligible to be scheduled on
nodeAffinity: {}
priorityClassName: ""
## Node selector
nodeSelector: {}
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
timezone: UTC
## Pod Disruption Budget is an indicator of the number of disruptions that can be tolerated at a given time.
podDisruptionBudget:
  maxUnavailable: 1
securityContext:
  supplementalGroups:
  - 206
  ext-app-launch-enabler:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    capabilities:
      drop:
      - all
      add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - SYSLOG
      - SETUID
      - SETGID
      - AUDIT_WRITE
  monitoring:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    capabilities:
      drop:
      - all
      add:
      - DAC_READ_SEARCH
      - DAC_OVERRIDE
      - FOWNER
      - SYS_ADMIN
      - SYS_RESOURCE
  waitInitContainer:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    capabilities:
      drop:
      - all
  httpd:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    capabilities:
      drop:
      - all
      add:
      - CHOWN
      - DAC_OVERRIDE
      - DAC_READ_SEARCH
      - FOWNER
      - FSETID
      - SETGID
      - SETUID
      - AUDIT_WRITE
      - SYSLOG
      - SYS_ADMIN
      - SYS_RESOURCE
spec:
  portHTTP: 8084
  portHTTPS: 8444
  portSSO: 8081
credmController:
  name: eric-enm-credm-controller
  port: 5001
jobs:
  jobAction: certrequest
  certRequest:
    imageName: enm-certrequestjob-container
    pullPolicy: Always
    tag: 1.52.0-33
    resources:
      requests:
        enabled: true
        cpu: 500m
        memory: 512Mi
      limits:
        enabled: true
        cpu: 1000m
        memory: 512Mi
